name: JavaCI

on: [push]

env:
  AZURE_WEBAPP_NAME: 575blockchain    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './build/libs/'      # set this to the path to your web app project, defaults to the repository root


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Server Build
      run: ./gradlew build
    - name: Server Test
      run: ./gradlew test
    - name: Front End npm install
      run: ( cd ./frontend && npm install )
    - name: Front End npm run build
      run: ( cd ./frontend && npm run build )
    - name: Copy Frontend Build to resources
      run: mkdir resources/static && cp -r frontend/build/* resources/static
    - name: Copy Resources
      run: cp -r ./resources ./build/libs/
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
